### ISSUE TITLE
WARNING: Application name is not set. Call Builder#setApplicationName.

### ISSUE THREAD

**Issue by mrksjs** [keensoft/alfresco-google-vision#1]
`WARNING: Application name is not set. Call Builder#setApplicationName.
Mar 17, 2016 10:36:03 PM com.google.api.client.googleapis.services.AbstractGoogleClient <init>
WARNING: Application name is not set. Call Builder#setApplicationName.
java.lang.NullPointerException
    at es.keensoft.alfresco.google.GoogleVisionExtractAction$GoogleVisionTask$1$1.execute(GoogleVisionExtractAction.java:111)
    at es.keensoft.alfresco.google.GoogleVisionExtractAction$GoogleVisionTask$1$1.execute(GoogleVisionExtractAction.java:96)
    at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:454)
    at es.keensoft.alfresco.google.GoogleVisionExtractAction$GoogleVisionTask$1.doWork(GoogleVisionExtractAction.java:135)
    at es.keensoft.alfresco.google.GoogleVisionExtractAction$GoogleVisionTask$1.doWork(GoogleVisionExtractAction.java:92)
    at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
    at org.alfresco.repo.security.authentication.AuthenticationUtil.runAsSystem(AuthenticationUtil.java:582)
    at es.keensoft.alfresco.google.GoogleVisionExtractAction$GoogleVisionTask.run(GoogleVisionExtractAction.java:92)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Mar 17, 2016 10:36:05 PM com.google.api.client.googleapis.services.AbstractGoogleClient <init>
`

i will try to dig into this tomorrow - just leaving this here as a memo :)

**Comment by angelborroy-ks** [comment]
It seems that is not possible to have a NullPointer at that line:

```
103:           GoogleVisionBean gvBean = googleVisionWorker.execute(reader);
104:                            
105:           // Labels
106:           for (String label : gvBean.getLabels()) {
107:               taggingService.addTag(nodeToBeGoogleVisioned, label);
108:           }
109:                    
110:           // Text
111:           if (gvBean.getText() != null && !gvBean.getText().isEmpty()) {

```

Nor gvBean or gvBean.getText() can be null.

**Comment by mrksjs** [comment]
you are right of course, line 111 does not make any sense looking at the checked in source, but when i decompiled the visionworker class from the repo.amp (from the download link) line 111 really points to
`Vision vision = getVisionService();`

**Comment by angelborroy-ks** [comment]
Good point!

I've updated our release by building a new AMP from checked source. Please, try with this one again.

**Comment by mrksjs** [comment]
:+1: :)
